version: '3'
services:
    web:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/src
        depends_on:
            - db
            - redis
        command: npm start
    
    db:
        image: mysql/mysql-server:8.0
        restart: always
        env_file:
            - secret.env
        ports:
            - 3309:3306
        volumes:
            - mysql_volume:/var/lib/mysql
            - .:/docker-entrypoint-initdb.d
        command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    redis:
        image: redis:6.2.1
        restart: always
        expose: 
            - 6379
        volumes:
            - redis_volume:/data
    
volumes:
    mysql_volume:
    redis_volume: